=== codesqueak/Nascom/emulator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by User (User) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:element name="EmulatorInformation">
        <xs:annotation>
            <xs:documentation>Comment describing your root element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Cards">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="Card">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Properties">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="Property">
                                                        <xs:complexType>
                                                            <xs:attribute name="Name" type="xs:string" use="required"/>
                                                            <xs:attribute name="Value" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="Class" type="xs:string" use="required"/>
                                    <xs:attribute name="Name" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== codesqueak/Nascom/emulatorInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<EmulatorInformation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emulator.xsd">


    <Cards>
        <Card Name="Nascom 2" Class="com.codingrodent.emulator.cards.nascom2cpu.Nascom2CPUCard">
            <Properties>
                <Property Name="VideoROM" Value="resources/hexdumpImages/ROM/system/CharacterGraphicsROM.nas"/>
                <Property Name="OperatingSystem" Value="resources/hexdumpImages/ROM/system/nassys1.nas"/>
                <Property Name="VideoRAMAddress" Value="0800"/>
                <Property Name="ScratchpadAddress" Value="0C00"/>
                <Property Name="StartAddress" Value="0000"/>

                <Property Name="BankAEnabled" Value="false"/>

                <Property Name="BankBEnabled" Value="false"/>

                <Property Name="nup" Value="false"/>
            </Properties>
        </Card>

    </Cards>

</EmulatorInformation>
